@startuml
Searcher --> (Register)
Owner --> (Register)
Owner -> (Add offer)
(Add offer) -- (modify)
(Add offer) -- (delete)
Searcher -> (Subscribe to an Offer)
(Subscribe to an Offer) -- (Modify)
(Subscribe to an Offer) -- (Delete)
Owner --> (See all Offers)
Searcher --> (See all Offers)
Admin --> (See all Offers)
Admin --> (Validate Offers)
(Validate Offers) -- (MODIFY)
(Validate Offers) -- (DELETE)

note "include" as N

(Validate Offers) .. N

(Add offer)  .. N

(Subscribe to an Offer) .. N

N .. (Authentication)

@enduml
